-
  name: 'cookie json'
  uriPattern: '{lang}.cookie.json'
  defaults:
    '@controller': 'Metadata'
    '@package': 'NeosRulez.CookieOptIn'
    '@action': 'metadata'
    '@format': 'json'
  appendExceedingArguments: true
